export const keywords = {"ചെയ്യുക": "do",
			 "ആണെങ്കിൽ":"if",
			 "ഇല്‍": "in",
			 "ഇന്": "for",
			 "ആവട്ടെ": "let",
			 "പുതിയ": "new",
			 "ശ്രമിക്കുക": "try",
			 "അസ്ഥിരം": "var",
			 "അവസ്ഥ": "case",
			 "അല്ലെങ്കിൽ": "else",
			 "എണ്ണല്‍": "enum",
			 "മൂല്യനിർണ്ണയം": "eval",
			 "അസാധു": "null",
			 "ഇത്": "this",
			 "ശരി": "true",
			 "വ്യർത്ഥം": "void",
			 "ഒപ്പം": "with",
			 "കാത്തിരിക്കുക": "await",
			 "മുടക്കുക": "break",
			 "പിടിക്കുക": "catch",
			 "ഗണം": "class",
			 "ശാശ്വതം": "const",
			 "തെറ്റ്": "false",
			 "ഉയര്‍ന്നതരം": "super",
			 "എറിയുക": "throw",
			 "എന്നിരിക്കെ": "while",
			 "നല്‍കുക": "yield",
			 "കളയുക": "delete",
			 "കയറ്റുമതി": "export",
			 "ഇറക്കുമതി": "import",
			 "പൊതു": "public",
			 "മടക്കം": "return",
			 "സ്ഥായി": "static",
			 "തിരിക്കുക": "switch",
			 "എത്തരം": "typeof",
			 "അടിസ്ഥാനം": "default",
			 "വ്യാപിപ്പിക്കുന്നു": "extends",
			 "ഒടുവിൽ": "finally",
			 "ഭാണ്‌ഡം": "package",
			 "സ്വകാര്യ": "private",
			 "തുടരുക": "continue",
			 "പ്രവർത്തി": "function",
			 "പ്രയോഗം": "function",
			 "തിരുത്തൽ": "debugger",
			 "വാദം": "arguments",
			 "സമ്പര്‍ക്കമുഖം": "interface",
			 "സുരക്ഷിതമാക്കപ്പെട്ട": "protected",
			 "നിർവഹിക്കുന്നു": "implements",
			 "ഉദാഹരണമാണ്": "instanceof"};

export const dataTypes = {};

export default keywords;
